# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://github.com/big-data-europe/docker-hadoop
# https://github.com/big-data-europe/docker-hadoop/issues/98


services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    env_file:
      - ./hadoop.env
    environment:
      CLUSTER_NAME: docker
    ports:
      - 9870:9870
      - 9002:9002
    networks:
      - scaleph

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - 9864:9864
      - 9866:9866
    networks:
      - scaleph

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9002 namenode:9870 datanode:9864 datanode:9866"
    ports:
      - 8088:8088
      - 8032:8032
      - 8030:8030
      - 8031:8031
    networks:
      - scaleph

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9002 namenode:9870 datanode:9864 datanode:9866 resourcemanager:8088"
    ports:
      - 8042:8042
    networks:
      - scaleph

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9002 namenode:9870 datanode:9864 datanode:9866 resourcemanager:8088"
    ports:
      - 8188:8188
    networks:
      - scaleph

networks:
  scaleph: