
webhook:
  create: false

image:
  repository: ghcr.io/flowerfine/flink-kubernetes-operator

defaultConfiguration:
  # If set to true, creates ConfigMaps/VolumeMounts. If set to false, no configuration will be created.
  # All below fields will be ignored if create is set to false.
  create: true
  # If set to true,
  #      (1) loads the built-in default configuration
  #      (2) appends the below flink-conf and logging configuration overrides
  # If set to false, loads just the overrides as in (2).
  # This option has not effect, if create is equal to false.
  append: true
  flink-conf.yaml: |+
    # Flink Config Overrides
    kubernetes.operator.metrics.reporter.slf4j.factory.class: org.apache.flink.metrics.slf4j.Slf4jReporterFactory
    kubernetes.operator.metrics.reporter.slf4j.interval: 5 MINUTE

    kubernetes.operator.reconcile.interval: 15 s
    kubernetes.operator.observer.progress-check.interval: 5 s
    
    kubernetes.operator.metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    kubernetes.operator.metrics.reporter.prom.port: 9999
    
    s3.endpoint: http://${IP}:9000
    s3.access-key: admin
    s3.secret-key: password
    s3.path.style.access: true

# (Optional) Exposes metrics port on the container if defined
metrics:
  port: 9999

# set TimeZone from UTC to Asia/Shanghai
operatorPod:
  env:
    - name: TZ
      value: Asia/Shanghai


