# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release-Docker-Scaleph-Master

on:
  workflow_dispatch:
  push:
    paths-ignore: ['docs/**', '**/*.md', '**/*.drawio', '**/*.svg']
    branches:
      - master

env:
  HUB: ghcr.io/flowerfine/scaleph

jobs:
  release:
    if: github.repository == 'flowerfine/scaleph'
    strategy:
      matrix:
        image: [ scaleph-api, scaleph-ui-react, scaleph-file-fetcher, mysql ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Fetch Project Version
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >>$GITHUB_ENV
      - name: Build scaleph-dist
        run: mvn -B -U -T 4C clean package -Pdist -DskipTests -Dfast
      - name: Build scaleph-ui-react-dist
        run: mvn -B -U package -pl scaleph-ui-react -am -DskipTests
      - name: Build scaleph-ui-react
        run: cd scaleph-ui-react && npm install && npm run build --prod
      - name: Build scaleph-file-fetcher
        run: mvn -B -U -T 4C clean package -Pdist -DskipTests -Dfast -am --projects scaleph-file-fetcher
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          no-cache: false
          cache-from: type=gha
          cache-to: type=gha
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: tools/docker/build/${{ matrix.image }}/Dockerfile
          tags: |
            ${{ env.HUB }}/${{ matrix.image }}:${{ env.PROJECT_VERSION }},
            ${{ env.HUB }}/${{ matrix.image }}:latest